package com.enums;

public enum EDbSqls {
    SELECT_USER_BY_LOGIN("SELECT * FROM TBL_USER WHERE LOGIN = ? LIMIT 1;"),
    SELECT_PASSWORD_BY_USER_ID("SELECT * FROM TBL_PASSWORD WHERE USER_ID_FK = ? ORDER BY PASSWORD_ID DESC LIMIT 1;"),
    SELECT_TOKEN_BY_USER_ID("SELECT * FROM TBL_TOKENS WHERE USER_ID_FK = ? ORDER BY TOKEN_ID DESC LIMIT 1;"),
    SELECT_TOKEN_BY_TOKEN("SELECT * FROM TBL_TOKENS WHERE TOKEN=? AND EXPIRATION_DATE>now();"),
    CHECK_IF_USER_ALREADY_IN_DB("select count(*) from TBL_USER where LOGIN = ? OR EMAIL = ? OR (USER_FIRSTNAME = ? AND USER_LASTNAME =?);"),
    GET_LAST_USER_CARD_ID("select USER_CARD_ID from TBL_USER ORDER BY USER_CARD_ID DESC LIMIT 1"),
    INSERT_TOKEN_INTO_DB("INSERT INTO TBL_TOKENS(TOKEN, EXPIRATION_DATE, USER_ID_FK) VALUES(?,?,?);"),
    INSERT_NEW_USER("INSERT INTO TBL_USER(USER_FIRSTNAME, USER_LASTNAME, LOGIN,EMAIL, USER_CARD_ID) VALUES(?, ?, ?, ?,?);"),
    INSERT_NEW_PASSWORD("INSERT INTO TBL_PASSWORD(PASSWORD_, USER_ID_FK) VALUES(?, ?); ");


    private String query;
    EDbSqls(String query){
        this.query = query;
    }

    public String getQuery() {
        return query;
    }
}
