package com.enums;

public enum EDbSqls {
    SELECT_USER_BY_LOGIN("SELECT * FROM TBL_USER WHERE LOGIN = ? LIMIT 1;"),
    SELECT_PASSWORD_BY_USER_ID("SELECT * FROM TBL_PASSWORD WHERE USER_ID_FK = ? ORDER BY PASSWORD_ID DESC LIMIT 1;"),
    SELECT_TOKEN_BY_USER_ID("SELECT * FROM TBL_TOKENS WHERE USER_ID_FK = ? ORDER BY TOKEN_ID DESC LIMIT 1;"),
    SELECT_TOKEN_BY_TOKEN("SELECT * FROM TBL_TOKENS WHERE TOKEN=? AND EXPIRATION_DATE>now();"),
    SELECT_BOOKS_FOR_USER("SELECT BOOK_ID,DATE_OF_HIRE, STATUS_, TITLE, AUTHOR, ISBN, BOOK_GENRE" +
            " FROM TBL_BOOK_HIRE bh" +
            " JOIN TBL_BOOKS b ON bh.BOOK_ID_FK = b.BOOK_ID" +
            " WHERE USER_ID_FK = ?;"),
    SELECT_USER_BY_ID("SELECT * FROM TBL_USER WHERE USER_ID = ?;"),
    SELECT_ALL_BOOKS("SELECT BOOK_ID,DATE_OF_HIRE, STATUS_, TITLE, AUTHOR, ISBN, BOOK_GENRE" +
            " FROM TBL_BOOKS b" +
            " LEFT JOIN TBL_BOOK_HIRE bh ON bh.BOOK_ID_FK = b.BOOK_ID" +
            " where USER_ID_FK is NULL;"),
    CHECK_IF_USER_ALREADY_IN_DB("select count(*) from TBL_USER where LOGIN = ? OR EMAIL = ? OR (USER_FIRSTNAME = ? AND USER_LASTNAME =?);"),
    GET_LAST_USER_CARD_ID("select USER_CARD_ID from TBL_USER ORDER BY USER_CARD_ID DESC LIMIT 1"),
    INSERT_TOKEN_INTO_DB("INSERT INTO TBL_TOKENS(TOKEN, EXPIRATION_DATE, USER_ID_FK) VALUES(?,?,?);"),
    INSERT_NEW_USER("INSERT INTO TBL_USER(USER_FIRSTNAME, USER_LASTNAME, LOGIN,EMAIL, USER_CARD_ID) VALUES(?, ?, ?, ?,?);"),
    INSERT_NEW_BOOK_HIRE("INSERT INTO TBL_BOOK_HIRE(DATE_OF_HIRE, STATUS_, USER_ID_FK, BOOK_ID_FK) VALUES(now(),'CHECKED',?,?);"),
    INSERT_NEW_PASSWORD("INSERT INTO TBL_PASSWORD(PASSWORD_, USER_ID_FK) VALUES(?, ?); ");


    private String query;
    EDbSqls(String query){
        this.query = query;
    }

    public String getQuery() {
        return query;
    }
}
